### PR TITLE
Fixed inconsistent data read issues and added new example

### PR DESCRIPTION
**Pull request by dewhisna**
- Fixed the inconsistent data read issue when reading values from the BME280 by doing the read as a single burst transfer as detailed in the Bosch Datasheet instead of register-by-register reads.  This mainly affected the humidity sensor reading, which previously caused it to return erroneous values.

- Switched the code to use 'normal mode' on the BME280 instead of 'forced mode' so that filtering and oversampling will work correctly.

- Added additional configuration modes for individually setting oversampling on all three sensors, and added filter and standby configuration options.

- Added new example program.

- Added .gitignore file

### CODE REVIEW

**Comment by moeskerv** [comment]
Well, seems to work good! Thanks a lot for the improvements!

**Comment by corny** [comment]
@microbuilder I would really appreciate merging the great work of dewhisna.

**Comment by corny** [comment]
Wow, thanks a lot!

**Comment by microbuilder** [comment]
Sorry for the slow work merging this in.

**Pull request merged**
