### PR TITLE
Functions for Fahrenheit and inHg, expanded examples

### PR DESCRIPTION
**Pull request by MS3FGX**
I'm working on a Pi-based weather station for uploading to Weather Underground, and their [Personal Weather Station (PWS) Protocol](http://wiki.wunderground.com/index.php/PWS_-_Upload_Protocol) only accepts temperatures in Fahrenheit and barometric pressure in inches of mercury (inHg).

So I added two simple functions which simply call the existing temperature/pressure commands and do the conversions automatically. I've also added an annotated example that demos the new functions as well as the existing ones.

### CODE REVIEW

**Comment by microbuilder** [comment]
Sorry for the extremely slow reply ... I'll be happy to merge this if you can bring the PR up to date with the latest published files?

**Comment by microbuilder** [comment]
Although ... it would be better to add an entirely new example if possible, rather than editing the existing one, maybe indicating it outputs F and inHg?

**Comment by MS3FGX** [comment]
Yeah I got you, a lot of things look to have changed since I originally made the PR. Give me a bit and I'll sort it out.

**Comment by MS3FGX** [comment]
So that should remove conflicts with the newer .gitignore and revert the example back to stock. It adds in my additional functions (which now includes dewpoint calculation) as well as another change I made post-PR which gives a slightly more useful error message to the user if they are trying to connect to the sensor without the appropriate permissions. Unless you would rather me drop that bit out and do that as a separate PR for organizational sake?

As for the examples, are we saying that the preferred method is to make now a third example file (I.E. now Adafruit_BME280_Example3.py)? If that's how you want to do it I have no problem with it, but does seem like it will get a bit ungainly if we make a new example each time somebody improves/adds to the base. 

Perhaps the example file would be better handled as an issue for a later date, when things have settled down a bit and one comprehensive example can be made?

**Comment by microbuilder** [comment]
The number system is ungainly, I agree. For the example, I was thinking something more like `Adafruit_BME280_Example_Imperial.py` but .... that's pretty ungainly as well to be fair. :) I did just rename `Example2` to `Example_Curses` though to make it clearer what the difference is.

**Comment by microbuilder** [comment]
Feel free to submit an example to merge in!

**Pull request merged**
